#example of application.yml
#これは開発用の設定です。
server.port: 8443
server.ssl.key-store: keystore.p12
server.ssl.key-store-password: taisho6339
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat

spring:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
    thymeleaf:
        cache: false
logging:
    level:
        org.hibernate.SQL: ERROR
        org.hibernate.type: ERROR

spring.profiles.include: env