#example of application.yml
#これは開発用の設定です。
server.port: 8080
spring:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
    thymeleaf:
        cache: false
logging:
    level:
        org.hibernate.SQL: ERROR
        org.hibernate.type: ERROR

spring.profiles.include: env